package net.pocrd.product.dao.generatedMapper;

import java.util.List;
import net.pocrd.product.dao.entity.DemoDTO;
import net.pocrd.product.dao.entity.DemoDTOExample;
import org.apache.ibatis.annotations.Param;

public interface DemoDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int countByExample(DemoDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int deleteByExample(DemoDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int insert(DemoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int insertSelective(DemoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    List<DemoDTO> selectByExample(DemoDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    DemoDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DemoDTO record, @Param("example") DemoDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DemoDTO record, @Param("example") DemoDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DemoDTO record);
}