package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AttributeValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.attr_id
     *
     * @mbggenerated
     */
    /** å±žæ€§id */
    private Integer attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.name
     *
     * @mbggenerated
     */
    /** å±žæ€§å€¼åç§° */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.data
     *
     * @mbggenerated
     */
    /** æ‰©å±•æ•°æ® */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.modified_at
     *
     * @mbggenerated
     */
    /** æ›´æ–°æ—¶é—´ */
    private Date modifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_attr_value.is_deleted
     *
     * @mbggenerated
     */
    /** è®°å½•æ˜¯å¦è¢«åˆ é™¤ */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.id
     *
     * @return the value of mt_product_attr_value.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.id
     *
     * @param id the value for mt_product_attr_value.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.attr_id
     *
     * @return the value of mt_product_attr_value.attr_id
     *
     * @mbggenerated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.attr_id
     *
     * @param attrId the value for mt_product_attr_value.attr_id
     *
     * @mbggenerated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.name
     *
     * @return the value of mt_product_attr_value.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.name
     *
     * @param name the value for mt_product_attr_value.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.data
     *
     * @return the value of mt_product_attr_value.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.data
     *
     * @param data the value for mt_product_attr_value.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.created_at
     *
     * @return the value of mt_product_attr_value.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.created_at
     *
     * @param createdAt the value for mt_product_attr_value.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.modified_at
     *
     * @return the value of mt_product_attr_value.modified_at
     *
     * @mbggenerated
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.modified_at
     *
     * @param modifiedAt the value for mt_product_attr_value.modified_at
     *
     * @mbggenerated
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_attr_value.is_deleted
     *
     * @return the value of mt_product_attr_value.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_attr_value.is_deleted
     *
     * @param isDeleted the value for mt_product_attr_value.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}