package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.id_path
     *
     * @mbggenerated
     */
    /** ç›®å½•è·¯å¾„ parent_lv1;parent_lv2;parent_lv3; */
    private String idPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.name
     *
     * @mbggenerated
     */
    /** ç±»ç›®å */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.rank
     *
     * @mbggenerated
     */
    /** æŽ’åºæƒé‡ */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.default_front_category
     *
     * @mbggenerated
     */
    /** é»˜è®¤å‰å°ç±»ç›®,åŠè§’é€—å·åˆ†éš”çš„ç±»ç›®å */
    private String defaultFrontCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.modified_at
     *
     * @mbggenerated
     */
    /** æ›´æ–°æ—¶é—´ */
    private Date modifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_category.is_deleted
     *
     * @mbggenerated
     */
    /** è®°å½•æ˜¯å¦è¢«åˆ é™¤ */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mt_product_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.id
     *
     * @return the value of mt_product_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.id
     *
     * @param id the value for mt_product_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.id_path
     *
     * @return the value of mt_product_category.id_path
     *
     * @mbggenerated
     */
    public String getIdPath() {
        return idPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.id_path
     *
     * @param idPath the value for mt_product_category.id_path
     *
     * @mbggenerated
     */
    public void setIdPath(String idPath) {
        this.idPath = idPath == null ? null : idPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.name
     *
     * @return the value of mt_product_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.name
     *
     * @param name the value for mt_product_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.rank
     *
     * @return the value of mt_product_category.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.rank
     *
     * @param rank the value for mt_product_category.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.default_front_category
     *
     * @return the value of mt_product_category.default_front_category
     *
     * @mbggenerated
     */
    public String getDefaultFrontCategory() {
        return defaultFrontCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.default_front_category
     *
     * @param defaultFrontCategory the value for mt_product_category.default_front_category
     *
     * @mbggenerated
     */
    public void setDefaultFrontCategory(String defaultFrontCategory) {
        this.defaultFrontCategory = defaultFrontCategory == null ? null : defaultFrontCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.created_at
     *
     * @return the value of mt_product_category.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.created_at
     *
     * @param createdAt the value for mt_product_category.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.modified_at
     *
     * @return the value of mt_product_category.modified_at
     *
     * @mbggenerated
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.modified_at
     *
     * @param modifiedAt the value for mt_product_category.modified_at
     *
     * @mbggenerated
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_category.is_deleted
     *
     * @return the value of mt_product_category.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_category.is_deleted
     *
     * @param isDeleted the value for mt_product_category.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}