package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Item implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.sku_id
     *
     * @mbggenerated
     */
    /**  */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.title
     *
     * @mbggenerated
     */
    /** äº§å“åç§° */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.subtitle
     *
     * @mbggenerated
     */
    /** å‰¯æ ‡é¢˜ */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.product_desc_id
     *
     * @mbggenerated
     */
    /** äº§å“æè¿° */
    private Integer productDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.specs_desc_id
     *
     * @mbggenerated
     */
    /** è§„æ ¼æè¿° */
    private Integer specsDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.support_desc_id
     *
     * @mbggenerated
     */
    /** å”®åŽæè¿° */
    private Integer supportDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.main_image_id
     *
     * @mbggenerated
     */
    /** ä¸»å›¾ */
    private Integer mainImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.resource
     *
     * @mbggenerated
     */
    /** å…¶ä»–èµ„æºid,åŠè§’é€—å·åˆ†éš” */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.is_mutiple
     *
     * @mbggenerated
     */
    /** 0 éžç»„åˆå•†å“, 1 ç»„åˆå•†å“ */
    private Byte isMutiple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.status
     *
     * @mbggenerated
     */
    /** itemçŠ¶æ€, 0 æ­£å¸¸, 1ç¦ç”¨ */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.modified_at
     *
     * @mbggenerated
     */
    /** æ›´æ–°æ—¶é—´ */
    private Date modifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_item.is_deleted
     *
     * @mbggenerated
     */
    /** è®°å½•æ˜¯å¦è¢«åˆ é™¤ */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.id
     *
     * @return the value of mt_product_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.id
     *
     * @param id the value for mt_product_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.sku_id
     *
     * @return the value of mt_product_item.sku_id
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.sku_id
     *
     * @param skuId the value for mt_product_item.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.title
     *
     * @return the value of mt_product_item.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.title
     *
     * @param title the value for mt_product_item.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.subtitle
     *
     * @return the value of mt_product_item.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.subtitle
     *
     * @param subtitle the value for mt_product_item.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.product_desc_id
     *
     * @return the value of mt_product_item.product_desc_id
     *
     * @mbggenerated
     */
    public Integer getProductDescId() {
        return productDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.product_desc_id
     *
     * @param productDescId the value for mt_product_item.product_desc_id
     *
     * @mbggenerated
     */
    public void setProductDescId(Integer productDescId) {
        this.productDescId = productDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.specs_desc_id
     *
     * @return the value of mt_product_item.specs_desc_id
     *
     * @mbggenerated
     */
    public Integer getSpecsDescId() {
        return specsDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.specs_desc_id
     *
     * @param specsDescId the value for mt_product_item.specs_desc_id
     *
     * @mbggenerated
     */
    public void setSpecsDescId(Integer specsDescId) {
        this.specsDescId = specsDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.support_desc_id
     *
     * @return the value of mt_product_item.support_desc_id
     *
     * @mbggenerated
     */
    public Integer getSupportDescId() {
        return supportDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.support_desc_id
     *
     * @param supportDescId the value for mt_product_item.support_desc_id
     *
     * @mbggenerated
     */
    public void setSupportDescId(Integer supportDescId) {
        this.supportDescId = supportDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.main_image_id
     *
     * @return the value of mt_product_item.main_image_id
     *
     * @mbggenerated
     */
    public Integer getMainImageId() {
        return mainImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.main_image_id
     *
     * @param mainImageId the value for mt_product_item.main_image_id
     *
     * @mbggenerated
     */
    public void setMainImageId(Integer mainImageId) {
        this.mainImageId = mainImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.resource
     *
     * @return the value of mt_product_item.resource
     *
     * @mbggenerated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.resource
     *
     * @param resource the value for mt_product_item.resource
     *
     * @mbggenerated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.is_mutiple
     *
     * @return the value of mt_product_item.is_mutiple
     *
     * @mbggenerated
     */
    public Byte getIsMutiple() {
        return isMutiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.is_mutiple
     *
     * @param isMutiple the value for mt_product_item.is_mutiple
     *
     * @mbggenerated
     */
    public void setIsMutiple(Byte isMutiple) {
        this.isMutiple = isMutiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.status
     *
     * @return the value of mt_product_item.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.status
     *
     * @param status the value for mt_product_item.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.created_at
     *
     * @return the value of mt_product_item.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.created_at
     *
     * @param createdAt the value for mt_product_item.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.modified_at
     *
     * @return the value of mt_product_item.modified_at
     *
     * @mbggenerated
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.modified_at
     *
     * @param modifiedAt the value for mt_product_item.modified_at
     *
     * @mbggenerated
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_item.is_deleted
     *
     * @return the value of mt_product_item.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_item.is_deleted
     *
     * @param isDeleted the value for mt_product_item.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}