package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Item_Sku implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_item_sku.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_item_sku.item_id
     *
     * @mbggenerated
     */
    /**  */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_item_sku.sku_id
     *
     * @mbggenerated
     */
    /**  */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_item_sku.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_item_sku.id
     *
     * @return the value of mtr_product_item_sku.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_item_sku.id
     *
     * @param id the value for mtr_product_item_sku.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_item_sku.item_id
     *
     * @return the value of mtr_product_item_sku.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_item_sku.item_id
     *
     * @param itemId the value for mtr_product_item_sku.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_item_sku.sku_id
     *
     * @return the value of mtr_product_item_sku.sku_id
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_item_sku.sku_id
     *
     * @param skuId the value for mtr_product_item_sku.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_item_sku.created_at
     *
     * @return the value of mtr_product_item_sku.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_item_sku.created_at
     *
     * @param createdAt the value for mtr_product_item_sku.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}