package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Sku_AttributeValue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_sku_attr_value.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_sku_attr_value.ref_spu_id
     *
     * @mbggenerated
     */
    /** ç›¸å…³spuid */
    private Integer refSpuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_sku_attr_value.sku_id
     *
     * @mbggenerated
     */
    /**  */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_sku_attr_value.attr_value_id
     *
     * @mbggenerated
     */
    /**  */
    private Integer attrValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtr_product_sku_attr_value.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_sku_attr_value.id
     *
     * @return the value of mtr_product_sku_attr_value.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_sku_attr_value.id
     *
     * @param id the value for mtr_product_sku_attr_value.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_sku_attr_value.ref_spu_id
     *
     * @return the value of mtr_product_sku_attr_value.ref_spu_id
     *
     * @mbggenerated
     */
    public Integer getRefSpuId() {
        return refSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_sku_attr_value.ref_spu_id
     *
     * @param refSpuId the value for mtr_product_sku_attr_value.ref_spu_id
     *
     * @mbggenerated
     */
    public void setRefSpuId(Integer refSpuId) {
        this.refSpuId = refSpuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_sku_attr_value.sku_id
     *
     * @return the value of mtr_product_sku_attr_value.sku_id
     *
     * @mbggenerated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_sku_attr_value.sku_id
     *
     * @param skuId the value for mtr_product_sku_attr_value.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_sku_attr_value.attr_value_id
     *
     * @return the value of mtr_product_sku_attr_value.attr_value_id
     *
     * @mbggenerated
     */
    public Integer getAttrValueId() {
        return attrValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_sku_attr_value.attr_value_id
     *
     * @param attrValueId the value for mtr_product_sku_attr_value.attr_value_id
     *
     * @mbggenerated
     */
    public void setAttrValueId(Integer attrValueId) {
        this.attrValueId = attrValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtr_product_sku_attr_value.created_at
     *
     * @return the value of mtr_product_sku_attr_value.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtr_product_sku_attr_value.created_at
     *
     * @param createdAt the value for mtr_product_sku_attr_value.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}