package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Spu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.id
     *
     * @mbggenerated
     */
    /** spu id */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.cate_back_id
     *
     * @mbggenerated
     */
    /** åŽå°ç±»ç›®å¶èŠ‚ç‚¹id */
    private Integer cateBackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.cate_front
     *
     * @mbggenerated
     */
    /** å‰å°ç±»ç›®,åŠè§’é€—å·åˆ†éš”çš„ç±»ç›®å */
    private String cateFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.brand_id
     *
     * @mbggenerated
     */
    /** å“ç‰Œid */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.type
     *
     * @mbggenerated
     */
    /** å•†å“ç±»åž‹ */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.title
     *
     * @mbggenerated
     */
    /** äº§å“åç§° */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.subtitle
     *
     * @mbggenerated
     */
    /** å‰¯æ ‡é¢˜ */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.product_desc_id
     *
     * @mbggenerated
     */
    /** äº§å“æè¿° */
    private Integer productDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.specs_desc_id
     *
     * @mbggenerated
     */
    /** è§„æ ¼æè¿° */
    private Integer specsDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.support_desc_id
     *
     * @mbggenerated
     */
    /** å”®åŽæè¿° */
    private Integer supportDescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.main_image_id
     *
     * @mbggenerated
     */
    /** ä¸»å›¾ */
    private Integer mainImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.resource
     *
     * @mbggenerated
     */
    /** å…¶ä»–èµ„æºid,åŠè§’é€—å·åˆ†éš” */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.status
     *
     * @mbggenerated
     */
    /** spuçŠ¶æ€, 0 æ­£å¸¸, 1ç¦ç”¨ */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.modified_at
     *
     * @mbggenerated
     */
    /** æ›´æ–°æ—¶é—´ */
    private Date modifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_spu.is_deleted
     *
     * @mbggenerated
     */
    /** è®°å½•æ˜¯å¦è¢«åˆ é™¤ */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mt_product_spu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.id
     *
     * @return the value of mt_product_spu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.id
     *
     * @param id the value for mt_product_spu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.cate_back_id
     *
     * @return the value of mt_product_spu.cate_back_id
     *
     * @mbggenerated
     */
    public Integer getCateBackId() {
        return cateBackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.cate_back_id
     *
     * @param cateBackId the value for mt_product_spu.cate_back_id
     *
     * @mbggenerated
     */
    public void setCateBackId(Integer cateBackId) {
        this.cateBackId = cateBackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.cate_front
     *
     * @return the value of mt_product_spu.cate_front
     *
     * @mbggenerated
     */
    public String getCateFront() {
        return cateFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.cate_front
     *
     * @param cateFront the value for mt_product_spu.cate_front
     *
     * @mbggenerated
     */
    public void setCateFront(String cateFront) {
        this.cateFront = cateFront == null ? null : cateFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.brand_id
     *
     * @return the value of mt_product_spu.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.brand_id
     *
     * @param brandId the value for mt_product_spu.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.type
     *
     * @return the value of mt_product_spu.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.type
     *
     * @param type the value for mt_product_spu.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.title
     *
     * @return the value of mt_product_spu.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.title
     *
     * @param title the value for mt_product_spu.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.subtitle
     *
     * @return the value of mt_product_spu.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.subtitle
     *
     * @param subtitle the value for mt_product_spu.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.product_desc_id
     *
     * @return the value of mt_product_spu.product_desc_id
     *
     * @mbggenerated
     */
    public Integer getProductDescId() {
        return productDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.product_desc_id
     *
     * @param productDescId the value for mt_product_spu.product_desc_id
     *
     * @mbggenerated
     */
    public void setProductDescId(Integer productDescId) {
        this.productDescId = productDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.specs_desc_id
     *
     * @return the value of mt_product_spu.specs_desc_id
     *
     * @mbggenerated
     */
    public Integer getSpecsDescId() {
        return specsDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.specs_desc_id
     *
     * @param specsDescId the value for mt_product_spu.specs_desc_id
     *
     * @mbggenerated
     */
    public void setSpecsDescId(Integer specsDescId) {
        this.specsDescId = specsDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.support_desc_id
     *
     * @return the value of mt_product_spu.support_desc_id
     *
     * @mbggenerated
     */
    public Integer getSupportDescId() {
        return supportDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.support_desc_id
     *
     * @param supportDescId the value for mt_product_spu.support_desc_id
     *
     * @mbggenerated
     */
    public void setSupportDescId(Integer supportDescId) {
        this.supportDescId = supportDescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.main_image_id
     *
     * @return the value of mt_product_spu.main_image_id
     *
     * @mbggenerated
     */
    public Integer getMainImageId() {
        return mainImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.main_image_id
     *
     * @param mainImageId the value for mt_product_spu.main_image_id
     *
     * @mbggenerated
     */
    public void setMainImageId(Integer mainImageId) {
        this.mainImageId = mainImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.resource
     *
     * @return the value of mt_product_spu.resource
     *
     * @mbggenerated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.resource
     *
     * @param resource the value for mt_product_spu.resource
     *
     * @mbggenerated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.status
     *
     * @return the value of mt_product_spu.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.status
     *
     * @param status the value for mt_product_spu.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.created_at
     *
     * @return the value of mt_product_spu.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.created_at
     *
     * @param createdAt the value for mt_product_spu.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.modified_at
     *
     * @return the value of mt_product_spu.modified_at
     *
     * @mbggenerated
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.modified_at
     *
     * @param modifiedAt the value for mt_product_spu.modified_at
     *
     * @mbggenerated
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_spu.is_deleted
     *
     * @return the value of mt_product_spu.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_spu.is_deleted
     *
     * @param isDeleted the value for mt_product_spu.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}