package net.pocrd.product.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class StaticResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.description
     *
     * @mbggenerated
     */
    /** èµ„æºæè¿° */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.type
     *
     * @mbggenerated
     */
    /** èµ„æºç±»åž‹ IMG, VIDEO, HTML */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.meta
     *
     * @mbggenerated
     */
    /** èµ„æºå…ƒä¿¡æ¯ */
    private String meta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.uri
     *
     * @mbggenerated
     */
    /** cdnèµ„æºè·¯å¾„ */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.created_at
     *
     * @mbggenerated
     */
    /** åˆ›å»ºæ—¶é—´ */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.modified_at
     *
     * @mbggenerated
     */
    /** æ›´æ–°æ—¶é—´ */
    private Date modifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_product_static_resource.is_deleted
     *
     * @mbggenerated
     */
    /** è®°å½•æ˜¯å¦è¢«åˆ é™¤ */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mt_product_static_resource
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.id
     *
     * @return the value of mt_product_static_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.id
     *
     * @param id the value for mt_product_static_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.description
     *
     * @return the value of mt_product_static_resource.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.description
     *
     * @param description the value for mt_product_static_resource.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.type
     *
     * @return the value of mt_product_static_resource.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.type
     *
     * @param type the value for mt_product_static_resource.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.meta
     *
     * @return the value of mt_product_static_resource.meta
     *
     * @mbggenerated
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.meta
     *
     * @param meta the value for mt_product_static_resource.meta
     *
     * @mbggenerated
     */
    public void setMeta(String meta) {
        this.meta = meta == null ? null : meta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.uri
     *
     * @return the value of mt_product_static_resource.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.uri
     *
     * @param uri the value for mt_product_static_resource.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.created_at
     *
     * @return the value of mt_product_static_resource.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.created_at
     *
     * @param createdAt the value for mt_product_static_resource.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.modified_at
     *
     * @return the value of mt_product_static_resource.modified_at
     *
     * @mbggenerated
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.modified_at
     *
     * @param modifiedAt the value for mt_product_static_resource.modified_at
     *
     * @mbggenerated
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_product_static_resource.is_deleted
     *
     * @return the value of mt_product_static_resource.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_product_static_resource.is_deleted
     *
     * @param isDeleted the value for mt_product_static_resource.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}