package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.AttributeValue;
import net.pocrd.product.dao.entity.AttributeValueExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AttributeValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @SelectProvider(type=AttributeValueSqlProvider.class, method="countByExample")
    int countByExample(AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @DeleteProvider(type=AttributeValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mt_product_attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mt_product_attr_value (id, attr_id, ",
        "name, data, created_at, ",
        "modified_at, is_deleted)",
        "values (#{id,jdbcType=INTEGER}, #{attrId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{data,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{modifiedAt,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT})"
    })
    int insert(AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @InsertProvider(type=AttributeValueSqlProvider.class, method="insertSelective")
    int insertSelective(AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @SelectProvider(type=AttributeValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attr_id", property="attrId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    List<AttributeValue> selectByExample(AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, attr_id, name, data, created_at, modified_at, is_deleted",
        "from mt_product_attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attr_id", property="attrId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    AttributeValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AttributeValue record, @Param("example") AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AttributeValue record, @Param("example") AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr_value
     *
     * @mbggenerated
     */
    @Update({
        "update mt_product_attr_value",
        "set attr_id = #{attrId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "data = #{data,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "modified_at = #{modifiedAt,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AttributeValue record);
}