package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.Attribute;
import net.pocrd.product.dao.entity.AttributeExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="countByExample")
    int countByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @DeleteProvider(type=AttributeSqlProvider.class, method="deleteByExample")
    int deleteByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mt_product_attr",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mt_product_attr (id, name, ",
        "data, created_at, ",
        "modified_at, is_deleted)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{data,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{modifiedAt,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT})"
    })
    int insert(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @InsertProvider(type=AttributeSqlProvider.class, method="insertSelective")
    int insertSelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    List<Attribute> selectByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, data, created_at, modified_at, is_deleted",
        "from mt_product_attr",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    Attribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_attr
     *
     * @mbggenerated
     */
    @Update({
        "update mt_product_attr",
        "set name = #{name,jdbcType=VARCHAR},",
          "data = #{data,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "modified_at = #{modifiedAt,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Attribute record);
}