package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.DisplayLabel;
import net.pocrd.product.dao.entity.DisplayLabelExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DisplayLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @SelectProvider(type=DisplayLabelSqlProvider.class, method="countByExample")
    int countByExample(DisplayLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @DeleteProvider(type=DisplayLabelSqlProvider.class, method="deleteByExample")
    int deleteByExample(DisplayLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mt_product_display_label",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mt_product_display_label (id, owner, ",
        "name, type, data, ",
        "res1_id, start_time, ",
        "end_time, created_at, ",
        "modified_at, is_deleted)",
        "values (#{id,jdbcType=INTEGER}, #{owner,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{type,jdbcType=TINYINT}, #{data,jdbcType=VARCHAR}, ",
        "#{res1Id,jdbcType=INTEGER}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{modifiedAt,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT})"
    })
    int insert(DisplayLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @InsertProvider(type=DisplayLabelSqlProvider.class, method="insertSelective")
    int insertSelective(DisplayLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @SelectProvider(type=DisplayLabelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="owner", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="res1_id", property="res1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    List<DisplayLabel> selectByExample(DisplayLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, owner, name, type, data, res1_id, start_time, end_time, created_at, modified_at, ",
        "is_deleted",
        "from mt_product_display_label",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="owner", property="owner", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="data", property="data", jdbcType=JdbcType.VARCHAR),
        @Result(column="res1_id", property="res1Id", jdbcType=JdbcType.INTEGER),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    DisplayLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DisplayLabelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DisplayLabel record, @Param("example") DisplayLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DisplayLabelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DisplayLabel record, @Param("example") DisplayLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @UpdateProvider(type=DisplayLabelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DisplayLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_display_label
     *
     * @mbggenerated
     */
    @Update({
        "update mt_product_display_label",
        "set owner = #{owner,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=TINYINT},",
          "data = #{data,jdbcType=VARCHAR},",
          "res1_id = #{res1Id,jdbcType=INTEGER},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "modified_at = #{modifiedAt,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DisplayLabel record);
}