package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.Item_Sku;
import net.pocrd.product.dao.entity.Item_SkuExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface Item_SkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @SelectProvider(type=Item_SkuSqlProvider.class, method="countByExample")
    int countByExample(Item_SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @DeleteProvider(type=Item_SkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(Item_SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mtr_product_item_sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mtr_product_item_sku (id, item_id, ",
        "sku_id, created_at)",
        "values (#{id,jdbcType=INTEGER}, #{itemId,jdbcType=INTEGER}, ",
        "#{skuId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Item_Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @InsertProvider(type=Item_SkuSqlProvider.class, method="insertSelective")
    int insertSelective(Item_Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @SelectProvider(type=Item_SkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Item_Sku> selectByExample(Item_SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, item_id, sku_id, created_at",
        "from mtr_product_item_sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Item_Sku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Item_SkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Item_Sku record, @Param("example") Item_SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Item_SkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Item_Sku record, @Param("example") Item_SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Item_SkuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Item_Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_item_sku
     *
     * @mbggenerated
     */
    @Update({
        "update mtr_product_item_sku",
        "set item_id = #{itemId,jdbcType=INTEGER},",
          "sku_id = #{skuId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Item_Sku record);
}