package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.Item;
import net.pocrd.product.dao.entity.ItemExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @SelectProvider(type=ItemSqlProvider.class, method="countByExample")
    int countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @DeleteProvider(type=ItemSqlProvider.class, method="deleteByExample")
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mt_product_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mt_product_item (id, sku_id, ",
        "title, subtitle, ",
        "product_desc_id, specs_desc_id, ",
        "support_desc_id, main_image_id, ",
        "resource, is_mutiple, ",
        "status, created_at, ",
        "modified_at, is_deleted)",
        "values (#{id,jdbcType=INTEGER}, #{skuId,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{productDescId,jdbcType=INTEGER}, #{specsDescId,jdbcType=INTEGER}, ",
        "#{supportDescId,jdbcType=INTEGER}, #{mainImageId,jdbcType=INTEGER}, ",
        "#{resource,jdbcType=VARCHAR}, #{isMutiple,jdbcType=TINYINT}, ",
        "#{status,jdbcType=TINYINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{modifiedAt,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT})"
    })
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @InsertProvider(type=ItemSqlProvider.class, method="insertSelective")
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @SelectProvider(type=ItemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="subtitle", property="subtitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_desc_id", property="productDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="specs_desc_id", property="specsDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="support_desc_id", property="supportDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="main_image_id", property="mainImageId", jdbcType=JdbcType.INTEGER),
        @Result(column="resource", property="resource", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_mutiple", property="isMutiple", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, sku_id, title, subtitle, product_desc_id, specs_desc_id, support_desc_id, ",
        "main_image_id, resource, is_mutiple, status, created_at, modified_at, is_deleted",
        "from mt_product_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="subtitle", property="subtitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_desc_id", property="productDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="specs_desc_id", property="specsDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="support_desc_id", property="supportDescId", jdbcType=JdbcType.INTEGER),
        @Result(column="main_image_id", property="mainImageId", jdbcType=JdbcType.INTEGER),
        @Result(column="resource", property="resource", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_mutiple", property="isMutiple", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_at", property="modifiedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT)
    })
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ItemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ItemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_product_item
     *
     * @mbggenerated
     */
    @Update({
        "update mt_product_item",
        "set sku_id = #{skuId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "product_desc_id = #{productDescId,jdbcType=INTEGER},",
          "specs_desc_id = #{specsDescId,jdbcType=INTEGER},",
          "support_desc_id = #{supportDescId,jdbcType=INTEGER},",
          "main_image_id = #{mainImageId,jdbcType=INTEGER},",
          "resource = #{resource,jdbcType=VARCHAR},",
          "is_mutiple = #{isMutiple,jdbcType=TINYINT},",
          "status = #{status,jdbcType=TINYINT},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "modified_at = #{modifiedAt,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Item record);
}