package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.Sku_AttributeValue;
import net.pocrd.product.dao.entity.Sku_AttributeValueExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface Sku_AttributeValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @SelectProvider(type=Sku_AttributeValueSqlProvider.class, method="countByExample")
    int countByExample(Sku_AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @DeleteProvider(type=Sku_AttributeValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(Sku_AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mtr_product_sku_attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mtr_product_sku_attr_value (id, ref_spu_id, ",
        "sku_id, attr_value_id, ",
        "created_at)",
        "values (#{id,jdbcType=INTEGER}, #{refSpuId,jdbcType=INTEGER}, ",
        "#{skuId,jdbcType=INTEGER}, #{attrValueId,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Sku_AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @InsertProvider(type=Sku_AttributeValueSqlProvider.class, method="insertSelective")
    int insertSelective(Sku_AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @SelectProvider(type=Sku_AttributeValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ref_spu_id", property="refSpuId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="attr_value_id", property="attrValueId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Sku_AttributeValue> selectByExample(Sku_AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, ref_spu_id, sku_id, attr_value_id, created_at",
        "from mtr_product_sku_attr_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ref_spu_id", property="refSpuId", jdbcType=JdbcType.INTEGER),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.INTEGER),
        @Result(column="attr_value_id", property="attrValueId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Sku_AttributeValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Sku_AttributeValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Sku_AttributeValue record, @Param("example") Sku_AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Sku_AttributeValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Sku_AttributeValue record, @Param("example") Sku_AttributeValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Sku_AttributeValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Sku_AttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_sku_attr_value
     *
     * @mbggenerated
     */
    @Update({
        "update mtr_product_sku_attr_value",
        "set ref_spu_id = #{refSpuId,jdbcType=INTEGER},",
          "sku_id = #{skuId,jdbcType=INTEGER},",
          "attr_value_id = #{attrValueId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Sku_AttributeValue record);
}