package net.pocrd.product.dao.mapper;

import java.util.List;
import net.pocrd.product.dao.entity.Spu_Attribute;
import net.pocrd.product.dao.entity.Spu_AttributeExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface Spu_AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @SelectProvider(type=Spu_AttributeSqlProvider.class, method="countByExample")
    int countByExample(Spu_AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @DeleteProvider(type=Spu_AttributeSqlProvider.class, method="deleteByExample")
    int deleteByExample(Spu_AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mtr_product_spu_attr",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mtr_product_spu_attr (id, ref_cate_back_id, ",
        "spu_id, attr_id, rank, ",
        "created_at)",
        "values (#{id,jdbcType=INTEGER}, #{refCateBackId,jdbcType=INTEGER}, ",
        "#{spuId,jdbcType=INTEGER}, #{attrId,jdbcType=INTEGER}, #{rank,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(Spu_Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @InsertProvider(type=Spu_AttributeSqlProvider.class, method="insertSelective")
    int insertSelective(Spu_Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @SelectProvider(type=Spu_AttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ref_cate_back_id", property="refCateBackId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="attr_id", property="attrId", jdbcType=JdbcType.INTEGER),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Spu_Attribute> selectByExample(Spu_AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, ref_cate_back_id, spu_id, attr_id, rank, created_at",
        "from mtr_product_spu_attr",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ref_cate_back_id", property="refCateBackId", jdbcType=JdbcType.INTEGER),
        @Result(column="spu_id", property="spuId", jdbcType=JdbcType.INTEGER),
        @Result(column="attr_id", property="attrId", jdbcType=JdbcType.INTEGER),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Spu_Attribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Spu_AttributeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Spu_Attribute record, @Param("example") Spu_AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Spu_AttributeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Spu_Attribute record, @Param("example") Spu_AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @UpdateProvider(type=Spu_AttributeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Spu_Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtr_product_spu_attr
     *
     * @mbggenerated
     */
    @Update({
        "update mtr_product_spu_attr",
        "set ref_cate_back_id = #{refCateBackId,jdbcType=INTEGER},",
          "spu_id = #{spuId,jdbcType=INTEGER},",
          "attr_id = #{attrId,jdbcType=INTEGER},",
          "rank = #{rank,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Spu_Attribute record);
}